;;; TODO: Compress graphics with tcpack
;;; TODO: Decompress to VRAM directly
;;; TODO: Change outi in TNI logo for a autogenerated RAM routine



%include "tniasm.inc"
%include "z80r800.inc"
%include "z80().inc"
%include "msx.inc"

%outfile "menace.rom"

orgcode 4000h
orgrdata 0E000h

pagsize equ	32*1024
p1size  equ     p1end-p1load
p1padd  equ     pagsize-p1size
p1sizeT equ     p1endf-p1load


section code

p1load:	equ	$
	db      'AB'
        dw      main
        dw      0,0,0,0,0,0




main:	call	SaveSlotC
	call	RomSlotPage2
	call	InitScore
	;ld	a,1fh
	;out	(02eh),a


game:
 	call	showLogo
 	call	initIntro
	call	initsound
	call	InitLevel
nextl:	call	PlayLevel
	cp	0
	call	z,showEnding
	cp	2
	jr	z,showGameOver
	jr	nextl


showGameOver:
	pop	hl
	ld	hl,game
	push	hl
	ret



showEnding:
	pop	hl
	ld	hl,game
	push	hl
	ret







%include "sound.asm"
%include "sys.asm"
%include "untcfv_msx1.asm"
%include "tnimsx1.asm"
%include "intro.asm"
%include "levels.asm"
%include "pj.asm"
%include "score.asm"
%include "enemy.asm"
%include "aysfx.asm"
%include "meteors.asm"
%include "pt3.asm"

sfx:
%incbin  "../sounds/sound.afb"
scrpat:
%incbin  "patterns.pat.tcf",8
scrcol:
%incbin  "patterns.col"
sprdata:
%incbin  "sprites.spr.tcf",8
floorpat:
%incbin  "floor.flr"
floorcol:
%incbin  "floor.col"
enemybin:
%incbin  "enemy.ene"
enemycol:
%incbin  "enemy.col"


p1end:	equ $
	ds      p1padd,0
p1endf: equ $

%if p1size > pagsize
   %warn "Page 0 boundary broken"
%endif

